"""stock

Revision ID: 95dab814b2c6
Revises: 
Create Date: 2025-04-21 14:56:16.026737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95dab814b2c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PRODUCTOS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Stock', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PRODUCTOS', schema=None) as batch_op:
        batch_op.drop_column('Stock')

    # ### end Alembic commands ###
